# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'iOSTecGet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Application
  pod 'AFNetworking','3.1.0'
  pod 'IQKeyboardManager','6.2.0'
  pod 'SDWebImage','4.3.3'
  pod 'MJRefresh', '3.1.12'
  pod 'MJExtension','3.0.13'
  pod 'Masonry'
end
