# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'



target 'iOSTecGet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Application
  pod 'AFNetworking','3.1.0'
  pod 'IQKeyboardManager','6.2.0'
  pod 'SDWebImage','4.3.3'
  pod 'MJRefresh', '3.1.12'
  pod 'MJExtension','3.0.13'
  pod 'Masonry'
  post_install do |installer|
    copy_pods_resources_path = "Pods/Target Support Files/Pods-iOSTecGet/Pods-iOSTecGet-resources.sh"
    string_to_replace = '--compile "{BUILT_PRODUCTS_DIR}/{UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
    assets_compile_with_app_icon_arguments = '--compile "{BUILT_PRODUCTS_DIR}/{UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "{ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "{BUILD_DIR}/assetcatalog_generated_info.plist"'
    text = File.read(copy_pods_resources_path)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
  end
end
